# User config
author: "Vishnu N K"
tagline: "Apps on Amazon Appstore"
# description: "In 1493, explorer Christopher Columbus found pineapples on Guadeloupe Island in the Caribbean. Pineapple on pizza soon followed..."
# keywords: "Pineapple, Pineapple Pizza, Pineapple House"
email: "visnkmr@gmail.com"
linkedin: "https://linkedin.com/in/vishnu-nanda-kumar-4a5a066b"
twitter: "https://twitter.com/visnkmr"
github: "https://github.com/visnkmr"

# Site config
baseurl: "/apps"
highlighter: rouge
sass:
  sass_dir: assets/scss
  style: compressed
